spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/users-rest
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 10000

user:
  age: 18